---
- name: Node Exporter
  docker_container:
    name: "{{ CONTAINER_NAME }}"
    image: "prom/node-exporter:{{ BUILD }}"
    command: --path.rootfs=/host
    network_mode: host
    pid_mode: host
    pull: "yes"
    recreate: "yes"
    cpu_period: "{{ DOCKER_CPU_PERIOD }}"
    cpu_quota: "{{ DOCKER_CPU_QUOTA }}"
    memory: "{{ DOCKER_MEMORY }}"
    state: "{{ CONTAINER_STATE }}"
    restart_policy: "unless-stopped"
    # published_ports:
    #  - "0.0.0.0:9100:9100"
    volumes:
      - /:/host:ro,rslave
  tags: 
  - asbrl-linux-node-exporter